server:
  port: 8080 #Tomcat端口

dubbo:
  application:
    name: the-provide
  registry:
    address: zookeeper://localhost #zookeeper地址
    port: 2181
    timeout: 5000 #提供注册的端口
  protocol:
    name: dubbo
    port: 20890
  scan:
    base-packages: com.athy.Service.Impl


