server:
  port: 8888 #Tomcat端口

dubbo:
  application:
    name: the-consumer
  registry:
    address: zookeeper://localhost #zookeeper地址
    port: 2181
    timeout: 10000
    check: true #注册中心启动时检查 (注册订阅失败时报错)
  protocol:
    name: dubbo #协议
    #serialization: dubbo
  scan:
    base-packages: com.athy.controller,com.athy.service.impl #扫描的包
  consumer:
    check: false #检查有没有provide提供服务